#!/usr/bin/env Rscript
library(optparse)
option_list <- list(
  make_option(c("-g", "--gff3"), action = "store", type = "character",
              help = "gff3  with LTR Transposable elements", default = NULL),
  make_option(c("-o", "--output"), action = "store", type = "character",
              help = "output file prefix", default = NULL),
  make_option(c("-a", "--save_all"), type = "logical", action="store_true", default = FALSE,
              help = "save all to .RData file")
)
description <- paste(strwrap(""))
epilogue <- ""
parser <- OptionParser(option_list = option_list, epilogue = epilogue, description =
  description, usage = "usage: %prog COMMAND [OPTIONS]")

opt <- parse_args(parser, args = commandArgs(TRUE))

# check is mandatory -g and -o options are provided
if (is.null(opt$gff3) || is.null(opt$output)){
  print_help(parser)
  stop("Mandatory options -g and -o are required")
}

suppressPackageStartupMessages(
{library(rtracklayer)
})


createHTMLHeader <- function(title = "DANTE LTR Summary", outputFile) {
  cat("<!DOCTYPE html>\n",
      "<html>\n",
      "<head>\n",
      "<title>", title, "</title>\n",
      "<style>\n",
      "body { font-family: Arial, sans-serif; display: flex; }\n",
      "#sidebar { width: 300px; background-color: #f2f2f2; padding: 10px; position: fixed; height: 100%; overflow: auto; }\n",
      "#main { margin-left: 330px; flex-grow: 1; }\n",
      "img { max-width: 100%; height: auto; }\n",
      "table { border-collapse: collapse; margin: left; align: left}\n",  # Adjusted table width
      "th, td { border: 1px solid #ddd; padding: 8px; text-align: left; vertical-align: middle; }\n",
      "td:nth-child(n) { text-align: right; }\n",  # Right aligns all cells, replace n with the column number for numeric data
      "tr:nth-child(even) { background-color: #f2f2f2; }\n",
      "th { padding-top: 12px; padding-bottom: 12px; background-color: #4CAF50; color: white; }\n",
      "</style>\n",
      "</head>\n",
      "<body id=\"top\">\n", file = outputFile, sep = "")
}


# Function to create the sidebar with links
createSidebar <- function(fileNames, outputFile) {
  cat("<div id='sidebar'>\n", file = outputFile, append = TRUE)
  cat("<p><a href='#top'>DANTE_LTR Summary</a></p>\n", file = outputFile, append = TRUE)
  for (name in names(fileNames)) {
    name_mod <- gsub(" summary$", " ", name)
    cat("<p><a href='#", gsub(" ", "_", name), "'>", name_mod, "</a></p>\n",
        file = outputFile, append = TRUE, sep = "")
  }
  cat("</div>\n", file = outputFile, append = TRUE)
}

# Function to create the main content area with all images
createMainContent <- function(fileNames, outputFile, folder, summary_df) {
  cat("<div id='main'>\n",
      "<h1>DANTE LTR Summary</h1>\n", file = outputFile, append = TRUE)
  cat(dataFrameToHTMLTable(summary_df), file = outputFile, append = TRUE)
  for (name in names(fileNames)) {
    cat("<h2 id='", gsub(" ", "_", name), "'>", name, "</h2>\n",
        "<img src='", folder, "/", basename(fileNames[name]), "' alt='", name, "'>\n",
        file = outputFile, append = TRUE, sep = "")
  }

  cat("</div>\n", file = outputFile, append = TRUE)
}

# Function to close the HTML document
closeHTML <- function(outputFile) {
  cat("</body>\n",
      "</html>", file = outputFile, append = TRUE, sep = "")
}

# Main function to generate the HTML file
generateHTML <- function(output_file_names, main_filename, folder, summary_df) {
  createHTMLHeader("DANTE LTR Summary", main_filename)
  sel <-  c(1,2,seq(3, length(output_file_names) - 1, by = 2))
  output_file_names2 <- output_file_names[sel]
  createSidebar(output_file_names2, main_filename)
  createMainContent(output_file_names, main_filename, folder, summary_df)
  closeHTML(main_filename)
}

dataFrameToHTMLTable <- function(df) {
  # Start the HTML table
  htmlTable <- "<table border='1'>\n"

  # Add the header row
  htmlTable <- paste0(htmlTable, "<tr>")
  for (columnName in names(df)) {
    htmlTable <- paste0(htmlTable, "<th>", columnName, "</th>")
  }
  htmlTable <- paste0(htmlTable, "</tr>\n")

  # Add the data rows
  for (row in 1:nrow(df)) {
    htmlTable <- paste0(htmlTable, "<tr>")
    for (value in df[row, ]) {
      htmlTable <- paste0(htmlTable, "<td>", value, "</td>")
    }
    htmlTable <- paste0(htmlTable, "</tr>\n")
  }

  # Close the HTML table
  htmlTable <- paste0(htmlTable, "</table>")

  return(htmlTable)
}




plot_multiple_elements <- function (segments_info, feature_colors){
  if (ncol(segments_info$segment_position) > 10000){
    print("Too many elements, ploting sample of 10000 elements")
    selected <- sample(1:ncol(segments_info$segment_position), 10000)
    segments_info$segment_position <- segments_info$segment_position[,selected]
    segments_info$segment_width <- segments_info$segment_width[,selected]
  }

  N <- ncol(segments_info$segment_width)
  NS <- nrow(segments_info$segment_width)
  max_length <- max(colSums(segments_info$segment_width, na.rm = TRUE), na.rm = TRUE)
  segment_name <-  names(segments_info$segment_mean_position)
  feature_names <- unique(sapply(strsplit(segment_name, " "), function(x) sub("_.+", "", x))[1,])

  col <-  feature_colors[sapply(strsplit(segment_name, " "),
                        function(x) paste(unique(sub("_.+", "", x)),
                                          collapse = "_"))]
  col[is.na(col)] <-  "#AAAAAA"
  # if segment info is too large hclust give error (cannot process more than 65536 elements)

  ord <- hclust(dist(t(segments_info$segment_position), method='man'), method = 'average')$order
  x1 <- c(segments_info$segment_position[,ord] - (segments_info$segment_width/2)[,ord])
  x2 <- c(segments_info$segment_position[,ord] + (segments_info$segment_width/2)[,ord])
  y1 <- c(sapply(1:N, rep, times = NS))
  y2 <- y1 + 1
  par(mfrow = c(1,1), mar=c(5,0.5,0.5,1))
  plot(0,0, type = "n", xlim = c(0, max_length*1.3), ylim = c(0, N+1), xlab = "", ylab = "", axes = FALSE)
  rect(rev(x1), rev(y1), rev(x2), rev(y2), col = rev(col), border = NA)
  axis(1, cex.axis = 1, las = 1, line = -1)
  mtext("Position [bp]", side = 1, line = 1.5, cex = 1)
  feature_names_formatted <- feature_names[feature_names !='LTR3']
  feature_colors_formatted <- feature_colors[feature_names_formatted]
  feature_names_formatted <- gsub("LTR5", "LTR", feature_names_formatted)

  feature_names_formatted['Missing domain'] <- 'Missing domain'
  feature_colors_formatted['Missing domain'] <- '#FFFFFF'
  # legen with no box around
  legend("topright", legend = feature_names_formatted,
         fill = feature_colors_formatted, cex = 1, bty = "n")
}


get_segment_info <- function(TE_long_rel_plot, TE_class, features){
  # features must be coreccly ordered
  SE <- c(rbind(paste0(features, "_S"), paste0(features, "_E")))
  SEpairs <- cbind(head(SE, -1), tail(SE, -1))
  TE <- TE_long_rel_plot[TE_long_rel_plot$classification == TE_class,]
  TE_byID <- split(TE, f = TE$TE_ID)
  starts_ends <- lapply(TE_byID, function(x) setNames(c(x$feature_start, x$feature_end),
                                                      c(paste0(x$TE_label, "_S"),
                                                       paste0(x$TE_label, "_E"))))
  segment_width <- sapply(starts_ends, function(x){
    out <- x[SEpairs[,2]] - x[SEpairs[,1]];
    names(out) <- paste(SEpairs[,1], SEpairs[,2]);
    out
  })

  segment_position <- sapply(starts_ends, function(x){
    out <- (x[SEpairs[,2]] + x[SEpairs[,1]])/2;
    names(out) <- paste(SEpairs[,1], SEpairs[,2]);
    out
  })
  segment_mean_position <- rowMeans(segment_position, na.rm = TRUE)
  return(list(segment_width = segment_width,
              segment_position = segment_position,
              segment_mean_position = segment_mean_position)
  )
}

segment_width2_start_end <- function(segments_info){
  sw <- segments_info$segment_width
  sw_median <- apply(sw,1, median, na.rm = TRUE)
  positions_SE <- cumsum(c("X LTR5_S" = 1, sw_median))
  SL <- grepl("S$", names(positions_SE))
  EL <- grepl("E$", names(positions_SE))
  label <- gsub("_.+$","",gsub(".+ ", "", names(positions_SE)))
  starts <- positions_SE[SL]; names(starts) <- label[SL]
  ends <- positions_SE[EL]; names(ends) <- label[EL]
  return(list(starts = starts, ends = ends))
}

feature_colors <- c("GAG" = "#fc850e",
                    "INT" = "#05fc09",
                    "LTR3" = "#333333",
                    "LTR5" = "#333333",
                    "PROT" = "#f80bfb",
                    "RH" = "#fc1413",
                    "RT" = "#0808f7",
                    "CHDCR" = "#7a001a",
                    "CHD" = "#20b5f4",
                    "aRH" = "#70403c")

plot_pbs_statistic <- function (pbs_info_part){
  pbs_info_e1 <- pbs_info_part
  pbs_info_e1$codon[pbs_info_part$evalue > 0.1] <- "Not found"
  pbs_info_e01 <- pbs_info_part
  pbs_info_e01$codon[pbs_info_part$evalue > 0.01] <- "Not found"
  all_codons <- unique(pbs_info_part$codon)
  codones <- data.frame( All = pbs_info_part$codon,
                        "evalue<0.1" = pbs_info_e1$codon,
                        "evalue<0.01" = pbs_info_e01$codon,
                        stringsAsFactors = FALSE,
                        check.names = FALSE)

  #codon_counts <- sapply(codones, function(x) table(factor(x, levels = all_codons)))
  codon_counts <- do.call(cbind,lapply(codones, function(x) table(factor(x, levels = all_codons))))
  # sort rows by total count
  codon_counts <- codon_counts[order(-rowSums(codon_counts)),,drop=FALSE]
  codon_counts2 <- cbind(codon_counts[,3], codon_counts[,1] - codon_counts[,3])
  # plot only most frequent codons
  Nmax <-  min(3, nrow(codon_counts2))
  if (Nmax == 0) {
    # there is nothing to plot, make empty plot
    plot(0,0, type = "n", axes = FALSE, xlab = "", ylab = "", main = "No PBS found")
  }else{
    codon_counts2 <- codon_counts2[1:Nmax,,drop=FALSE]
    ylims <- c(0, max(rowSums(codon_counts2)) * 1.6)
    labs <- rownames(codon_counts)[1:Nmax]
    vals <- codon_counts[1:Nmax,1]
    names(vals) <- labs
    barplot(vals, beside = FALSE, las=1, horiz = FALSE,
            main = "The most frequent PBS ", ylim = ylims, ylab = "Count",
            xlim = c(0,5)
    )
  }
}


plot_te <- function(colors, segments_info, title, pbs_info, ltr_identity){
  # plot TE features
  # inputs are starts, ends, colors
  # starts and ends are vectors of same length
  # colors is a vector of colors
  # output is a plot

  # test different calculation of starts and ends of segments
  starts_ends <- segment_width2_start_end(segments_info)

  starts <- starts_ends$starts
  ends <- starts_ends$ends
  # interlace starts and ends
  se_interlaced <- c(rbind(starts, ends))
  se1 <- se_interlaced[1:(length(se_interlaced)-1)]
  se2 <- se_interlaced[2:length(se_interlaced)]
  segment_mean_position2 <- (se1 + se2)/2

  boxplot_stats <- apply(segments_info$segment_width, 1, boxplot.stats)
  N <- dim(segments_info$segment_position)[2]
  max_val <- max(apply(segments_info$segment_width, 1, quantile, probs=1, na.rm=TRUE), na.rm=TRUE)

  segment_name <-  names(segments_info$segment_mean_position)
  col <-  colors[sapply(strsplit(segment_name, " "),
                        function(x) paste(unique(sub("_.+", "", x)),
                                          collapse = "_"))]
  col_domains_only <- col
  col[is.na(col)] <-  "#AAAAAA"
  W <- 100 * max(ends/7000)
  W2 <- 10 * max(ends/7000)
  #layout(matrix(c(0,0,3,1,2,3,4,4,4,0,0,0,5,5,5,6,6,6), ncol=3, byrow = TRUE), heights = c(0.5, 1.2, 0.8 ,0.5, 2, 1 ))
  layout(matrix(c(0,0,0,0,1,2,3,4, 5,5,5,5,0,0,0,0,6,6,6,6,7,7,7,7), ncol=4, byrow = TRUE)
, heights = c(0.5, 1.2, 0.7 ,0.2, 1.5, 1 ))
  ND <- nrow(segments_info$segment_position)
  par(mar = c(5,5,3,2), cex=0.8, las=1)
  # plot histogram of TE lengths
  # hist(segments_info$segment_position[ND,] - segments_info$segment_position[1,], main='Full element', breaks=200, border=NA, col="#AAAAAA", xlab = "length [nt]")
  # make breaks manually
  SW <- colSums(segments_info$segment_width)
  if (all(is.na(SW))){
    # no element is complete, make empty plot
    plot(0,0, type = "n" , axes = FALSE, xlab = "", ylab = "", main = "No full elements found")
  }else{
    brks <- seq(min(SW, na.rm = TRUE)-1000, max(SW, na.rm = TRUE) + 1000, length.out = 70)
    hist(SW, main='Element length', breaks=brks, border=NA, col="#AAAAAA", xlab = "[nt]")
  }


  # tile for page
  mtext(side = 3, text = paste0(title, " (N = ", N, ")"), line = 5, cex=1.5, adj = 0)

  LW <-  segments_info$segment_width[1,]
  brks <- seq(min(LW, na.rm = TRUE)-1000, max(LW, na.rm = TRUE) + 1000, length.out = 70)
  hist(LW, main='LTR length ', breaks=brks, border=NA, col="#AAAAAA", xlab = "[nt]", xlim = c(0, max(brks)))
  hist(ltr_identity, main='LTR identity', breaks=c(0:101), border=NA, col="#AAAAAA", xlab = "[%]", xlim = c(50,100))
  plot_pbs_statistic(pbs_info)
  ext <- 1.1
  # plot number of missing segments
  missing <- apply(segments_info$segment_width, 1, function(x) sum(is.na(x)))
  # plot it only for domains and ltr use rectangles
  par(mar = c(0,6,4,0.5))
  M <- max(missing)
  plot(segments_info$segment_mean_position, missing, type = "n", xlab = "",
       ylab = "", lwd=5, col=col_domains_only, axes = FALSE,
       ylim = c(0, M *1.5), xlim = c(0, max(ends)* ext))

  #horizontal ylabel
  mtext(3, text= "Number of missing domains", las=1, cex=1, line = 0, adj = 0.5)
  abline(h = c(0,N), col='lightgrey')

  rect(segment_mean_position2 - W, 0,
       segment_mean_position2 + W, missing, col=col_domains_only, border=NA)

  # add number of missing segments as text
  # show only for domains!
  include <- which(!is.na(col_domains_only)); include <- include[c(-1, -length(include))]


  text(segment_mean_position2[include], missing[include], labels = missing[include], pos = 3, cex = 0.8)


  x <- segments_info$segment_mean_position
  y <- rep(0.5, length(x))

  par(mar = c(0,5,0,0.5))
  plot(x,y, xlim = c(0, max(ends)* ext), ylim=c(0,max_val * 1.2), xlab = "", ylab = "Region width [nt]\n",
       axes = FALSE, type = "n")
  mtext(3, , text="   Feature size variation", line=-2, adj=0.5)
  # box()
  axis(side=2, las=1)

  for (i in seq_along(x)){
    # set color, grey if interstitial region, otherwise domain/ltr color

    centre <- segment_mean_position2[i]
    # make boxplot from boxplot stats at the centre of the segment
    bs <- boxplot_stats[[i]]$stats
    # horizontal median line
    segments(centre + W + W2, bs[3], centre - W - W2, bs[3], lwd=1, col=col[i])
    # vertical lines at quartiles
    # boxes for quartiles
    rect(centre - W, bs[2], centre + W, bs[4], border = NA, col = col[i])
    # vertical lines at min and max
    segments(centre, bs[1], centre, bs[5], lwd=3, col=col[i])
    # add whiskers
    segments(centre - W/2, bs[1], centre + W/2, bs[1], lwd=1, col=col[i])
    segments(centre - W/2, bs[5], centre + W/2, bs[5], lwd=1, col=col[i])

    # plot outliers is any
    if (!is.null(boxplot_stats[[i]]$out)){
      points(rep(centre, length(boxplot_stats[[i]]$out)), boxplot_stats[[i]]$out, pch=18, cex=0.5, col=paste0(col[i], "66"))
    }

  }
  element_scheme_coords <- list()

  par(mar=c(5,5,0,0))
  plot(0, 0, type = "n", xlim = c(0, max(ends)*ext), ylim = c(0, 10), xlab = "", ylab = "", axes = FALSE)
  mtext(side = 3, text="   Structure of average element", line=-2, adj=0.5)
  element_scheme_coords$xlim <- c(0, max(ends))
  element_scheme_coords$ylim <- c(0, 10)

  rect(0, 5, max(ends), 7, col = "#AAAAAA", border = NA)
  for (i in rev(names(starts))){
    element_scheme_coords[[i]] <- c(starts[i], ends[i])
    lab <- i
    wf <- 0
    if (i=="LTR3"){
      lab <- "3'LTR"
      wf <- 0.2
    }
    if (i=="LTR5"){
      lab <- "5'LTR"
      wf <- 0.2
    }
    rect(starts[i], 5 - wf, ends[i], 7 + wf, col = colors[i], border = "#00000000")
    text((starts[i] + ends[i])/2, 3, labels = lab, cex = 1, col = "#000000")
  }


  axis(1, cex.axis = 1, las = 1)
  mtext("Position [nt]", side = 1, line = 2.3, cex = 1)
  return(element_scheme_coords)
}


# FOR TESTING
if (FALSE){
  opt <- list()
  opt$gff3 <- "/mnt/raid/454_data/dante/execution_time_benchmark/dante_run/rice_v7_dante_ltr.gff3"
  opt$reference_sequence <- "/mnt/raid/users/petr/workspace/dante_ltr/test_data/sample_genome.fasta"
  opt$output <- "/mnt/raid/users/petr/workspace/dante_ltr/tmp/test_summary"
  opt$gff3 <- "/mnt/raid/454_data/dante/execution_time_benchmark/dante_run/B73_dante_ltr_epyc.gff3"
  opt$gff3 <- "/mnt/raid/454_data/dante/V_faba_test/dante_ltr_30cac496.gff3"
}

g <-  import(opt$gff3, format = "gff3")
g_te <- g[g$type == "transposable_element" & g$Rank != 'D',]
LTR_Identity <- sapply(split(g_te$LTR_Identity, g_te$Name), as.numeric)


x <- gc(verbose = FALSE)


TE_ID <- unlist(ifelse(is.na(g$ID), g$Parent, g$ID))

ID2Name <- g$Name[!is.na(g$ID)]; names(ID2Name) <- g$ID[!is.na(g$ID)]
# start and end of whole transposable element:
TE_start <- start(g)[!is.na(g$ID)]
TE_end <- end(g)[!is.na(g$ID)]
TE_strand <- as.vector(strand(g)[!is.na(g$ID)])
names(TE_start) <- g$ID[!is.na(g$ID)]
names(TE_end) <- g$ID[!is.na(g$ID)]
names(TE_strand) <- g$ID[!is.na(g$ID)]

is_partial <- grepl("partial", TE_ID)

# convert to table with format:
# TE_ID, Name, Feature_type(RT,RH,LTR5,..), start, end, strand, is_partial
TE_long <- data.frame(TE_ID = TE_ID,
                      classification = ID2Name[TE_ID],
                      Name = g$Name,
                      feature_type = as.character(g$type),
                      feature_start = start(g),
                      feature_end = end(g),
                      strand = as.character(strand(g)),
                      is_partial = is_partial,
                      te_start = TE_start[TE_ID],
                      te_end = TE_end[TE_ID],
                      te_strand = TE_strand[TE_ID],
                      stringsAsFactors = FALSE
)

# use te_strand, te_start and te_end to convert to relative coordinates of TE starting from 1
TE_long_rel <- TE_long
# consider strandness
TE_long_rel$feature_start <- ifelse(TE_long$te_strand == "+",
                                    TE_long$feature_start - TE_long$te_start + 1,
                                    TE_long$te_end - TE_long$feature_end + 1)
TE_long_rel$feature_end <- ifelse(TE_long$te_strand == "+",
                                    TE_long$feature_end - TE_long$te_start + 1,
                                    TE_long$te_end - TE_long$feature_start + 1)

TE_label <- TE_long_rel$Name
TE_label[is.na(TE_long_rel$Name)] <- TE_long_rel$feature_type[is.na(TE_long_rel$Name)]
TE_label[TE_long_rel$feature_type == 'long_terminal_repeat' & TE_long_rel$feature_start==1] <- "LTR5"
TE_label[TE_long_rel$feature_type == 'long_terminal_repeat' & TE_long_rel$feature_start>1] <- "LTR3"

TE_long_rel$TE_label <- TE_label

TE_long_rel_plot <- TE_long_rel[
  !TE_long_rel$feature_type %in% c('transposable_element',
                                   'target_site_duplication',
                                   'primer_binding_site') & !TE_long_rel$is_partial,
]

TE_long_rel_plot$center <- (TE_long_rel_plot$feature_start + TE_long_rel_plot$feature_end)/2
TE_long_rel_plot$width <- TE_long_rel_plot$feature_end - TE_long_rel_plot$feature_start


# convert to wide format, where each rows are TE_ID, colnames are TE_label and values are center.

TE_groups <- split(TE_long_rel_plot, f = paste(TE_long_rel_plot$classification ,TE_long_rel_plot$TE_label))

TE_groups_mean_start <- sapply(TE_groups, function(x) mean(x$feature_start))
TE_groups_mean_end <- sapply(TE_groups, function(x) mean(x$feature_end))
TE_lineage <- sapply(strsplit(names(TE_groups)," "), function(x)x[[1]])
TE_feature <- sapply(strsplit(names(TE_groups)," "), function(x)x[[2]])
# split to lineages:
TE_groups_mean_start_lineage <- sapply(split(TE_groups_mean_start, f = TE_lineage), function(x) {n <- gsub(".+ ", "", names(x)); names(x) <- n; sort(x)})
TE_groups_mean_end_lineage <- sapply(split(TE_groups_mean_end, f = TE_lineage), function(x) {n <- gsub(".+ ", "", names(x)); names(x) <- n; sort(x)})

# extract pbs info for intact elements
pbs_only <- g[g$type == 'primer_binding_site']

pbs_info <- data.frame(TE_ID= unique(TE_long_rel_plot$TE_ID),
                       tRNA = pbs_only$trna_id[match(unique(TE_long_rel_plot$TE_ID), unlist(pbs_only$Parent))],
                       evalue = as.numeric(pbs_only$evalue[match(unique(TE_long_rel_plot$TE_ID), unlist(pbs_only$Parent))]),
                       lineage_full_name = ID2Name[unique(TE_long_rel_plot$TE_ID)],
                       stringsAsFactors = FALSE)
pbs_info$lineage <- gsub(".+[|]", "", pbs_info$lineage_full_name)
pbs_info$codon <- gsub("-.+", "", gsub(".+__","",pbs_info$tRNA))
pbs_info$codon[is.na(pbs_info$codon)] <- "Not found"
# hemi start with lower case nucleotides
pbs_info$hemi <- grepl("^[actg]+", pbs_info$tRNA)

TE_ID_with_TSD <- unlist(g[g$type=="target_site_duplication"]$Parent)
TE_ID_with_PBS <- unlist(g[g$type=="primer_binding_site"]$Parent)
TE_ID_rank_DL <- unlist(g[g$Rank=="DL"]$ID)
TE_ID_rank_D <- unlist(g[g$Rank=="D"]$ID)

tsd_present <- TE_long_rel_plot$TE_ID %in% TE_ID_with_TSD
# same stats but only for Lienages with identified PBS
TE_long_rel_plot_with_pbs <- TE_long_rel_plot[tsd_present & TE_long_rel_plot$TE_ID %in% pbs_info$TE_ID[pbs_info$evalue<0.5 & pbs_info$codon!="Not found" ],]
TE_groups_with_pbs <- split(TE_long_rel_plot_with_pbs, f = paste(TE_long_rel_plot_with_pbs$classification ,TE_long_rel_plot_with_pbs$TE_label))
TE_groups_mean_start_with_pbs <- sapply(TE_groups_with_pbs, function(x) mean(x$feature_start))
TE_groups_mean_end_with_pbs <- sapply(TE_groups_with_pbs, function(x) mean(x$feature_end))
TE_lineage_with_pbs <- sapply(strsplit(names(TE_groups_with_pbs)," "), function(x)x[[1]])
TE_feature_with_pbs <- sapply(strsplit(names(TE_groups_with_pbs)," "), function(x)x[[2]])
# split to lineages:
TE_groups_mean_start_lineage_with_pbs <- sapply(split(TE_groups_mean_start_with_pbs, f = TE_lineage_with_pbs),
                                                function(x) {n <- gsub(".+ ", "", names(x)); names(x) <- n; sort(x)})
TE_groups_mean_end_lineage_with_pbs <- sapply(split(TE_groups_mean_end_with_pbs, f = TE_lineage_with_pbs), function(x) {n <- gsub(".+ ", "", names(x)); names(x) <- n; sort(x)})


L <- sort(unique(TE_lineage))

g_te <- g[g$type == "transposable_element"]
Lineage_counts2 <- as.matrix(table(g_te$Name,g_te$Rank))
# remove absent elements
Lineage_counts2 <- Lineage_counts2[rowSums(Lineage_counts2[,c("DL","DLT","DLP", "DLTP")]) > 0,]
Number_of_elements2 <- data.frame(
  "N_elements" = rowSums(Lineage_counts2[,c("DL","DLT","DLP", "DLTP")]),
  "N_elements_PBS_TSD" = Lineage_counts2[, "DLTP"],
  "N_elements_PBS" = Lineage_counts2[, "DLP"],
  "N_elements_TSD" = Lineage_counts2[, "DLT"]
)

Lineage_counts <- list(
  no_LTR=table(factor(ID2Name[TE_ID_rank_D], levels = L)),
  LTR=table(factor(ID2Name[TE_ID_rank_DL], levels = L)),
  PBS=table(factor(ID2Name[TE_ID_with_PBS], levels = L)),
  TSD=table(factor(ID2Name[TE_ID_with_TSD], levels = L)),
  PBS_TSD=table(factor(ID2Name[intersect(TE_ID_with_PBS, TE_ID_with_TSD)], levels = L)))
Lineage_counts <- do.call(rbind, Lineage_counts)
colnames(Lineage_counts) <- gsub("Class_I|LTR|", "", colnames(Lineage_counts), fixed = TRUE)

te_coords <- list()

pdf_out <- paste(opt$output, ".pdf", sep = "")
dir_out <- paste(opt$output, "_plots", sep = "")
dir.create(dir_out, showWarnings = FALSE)
output_file_names <- c(
  "Number of elements" =  paste0(dir_out, "/", 'number_of_elements.png'
))
output_file_names['TE structure summary and LTR identity'] <- paste0(dir_out, "/", "all_elements.png")


count_for_barplot <- Number_of_elements2
count_for_barplot$N_elements_rest <- with(Number_of_elements2, N_elements - N_elements_PBS - N_elements_TSD - N_elements_PBS_TSD)
count_for_barplot$N_elements <- NULL
# rows in reverse order
count_for_barplot <- count_for_barplot[nrow(count_for_barplot):1,]
# shorten names
rownames(count_for_barplot) <- gsub("Class_I|LTR|", "", rownames(count_for_barplot), fixed = TRUE)

png(file = output_file_names["Number of elements"], width = 1200, height = 600)
par(mfrow = c(1,1), mar=c(5,20,2,2), cex=1.2, cex.axis = 1, cex.lab = 1.2, cex.main = 1.2, cex.sub = 0.8)
xlims <- c(0, max(rowSums(count_for_barplot))*1.2)
barplot(t(count_for_barplot), beside = FALSE,
        legend.text = c("PBS & TSD", "PBS only", "TSD only", "Without PBS & TSD"),
        args.legend = list(x = "topright", bty = "n", cex = 1.5),
        horiz = TRUE,
        col = c("#000000", "#888888", "#BBBBBB", "#EEEEEE"),
        xlab = "Number of elements", las = 1,
        xlim = xlims
        )
dev.off()

for (i in seq_along(TE_groups_mean_end_lineage)){

  n <- names(TE_groups_mean_end_lineage)[[i]]
  # sanityze file name - remove special characters
  n2 <- gsub("[^[:alnum:]]", "_", n)

  png1 <- paste0(dir_out, "/", n2, "_summary.png")
  png2 <- paste0(dir_out, "/", n2, "_structure.png")
  title1 <- paste0(n, " summary")

  title2 <- paste0(gsub(".+[|]", "", n), " : Structure of individual elements")
  output_file_names[title1] <- png1
  output_file_names[title2] <- png2
  segments_info <-  get_segment_info(TE_long_rel_plot, names(TE_groups_mean_end_lineage)[[i]], features = names(TE_groups_mean_start_lineage[[i]]))
  if (n %in% TE_long_rel_plot_with_pbs$classification){
    segments_info_pbs <-  get_segment_info(TE_long_rel_plot_with_pbs, names(TE_groups_mean_end_lineage)[[i]], features = names(TE_groups_mean_start_lineage[[i]]))
  }else{
    segments_info_pbs <- NULL
  }
  pbs_info_part <- pbs_info[which(pbs_info$lineage_full_name == n & pbs_info$codon !='Not found'),,drop=FALSE]
  png(file = png1, width = 1500, height = 1200, pointsize = 20)
  te_coords[[n]] <- plot_te(feature_colors[TE_feature],
                            segments_info,
                            title = gsub("Class_I|LTR|", "", n, fixed = TRUE),
                            pbs_info_part,
                            LTR_Identity[[n]]
  )
  dev.off()

  if (ncol(segments_info$segment_width) > 1){
    png(file = png2, width = 1000, height = 1000, pointsize = 20)
    plot_multiple_elements(segments_info, feature_colors)
    dev.off()
  }
}
# plot all te from te coords
N <- length(te_coords)
xlim <- range(sapply(te_coords, function(x) x$xlim))


png(file = output_file_names['TE structure summary and LTR identity'], width = 1500, height = 1300)
layout(matrix(c(1,3,2), ncol=3), widths = c(5,1,1))
par(mar = c(4,0,2,0), cex=1.2)
offset <- 3000
plot(0,0, type = "n", xlim = c(-offset, xlim[2]), ylim = c(1, N+1), xlab = "", ylab = "", axes = FALSE)
ticks <- pretty(xlim, 10)
axis(1, at=ticks, cex.axis = 1, line = 0)
mtext("Position [nt]", 1, line = 2.5, cex = 1.5)
abline(v = ticks, lty = 3)
for (i in 1:N){
  n <- names(te_coords)[[N + 1 -i]]
  rect(te_coords[[n]]$xlim[1], i+0.25, te_coords[[n]]$xlim[2], i+.6, col = "#AAAAAA", border = NA)
  for (j in (names(te_coords[[n]])[-c(1,2)])){
    if (j %in% c("LTR3", "LTR5")){
      rect(te_coords[[n]][[j]][1], i+0.20, te_coords[[n]][[j]][2], i+0.65, col = feature_colors[j], border = "#000000")
    }else{
      rect(te_coords[[n]][[j]][1], i+0.25, te_coords[[n]][[j]][2], i+0.6, col = feature_colors[j], border = "#000000")
    }

    #text((te_coords[[n]][[j]][1] + te_coords[[n]][[j]][2])/2, i-0.1, labels = j, cex = 0.3, col = "#000000")
  }
  text(-offset/2, i+0.4125, labels = gsub(".+[|]", "",n) , cex=1.5)
}
# add legend
# legend(x = xlim[2], y = N+1, legend = names(feature_colors), fill = feature_colors, cex = 1.5, bty = "n")


# create histograms manually from rectangles
par(mar = c(4,3,2,1))
plot(0,0, type = "n", xlim = c(60, 100), ylim = c(1, N+1), xlab = "", ylab = "",
     axes = FALSE, main="LTR identity")
axis(1, line=0)
mtext("[%]", 1, line = 2.5, cex = 1.5)
mtext("Frequency", 2, line = -.1, cex = 1.5)
for (i in 1:N){
  j <- N + 1 - i
  hist_data <- hist(LTR_Identity[[i]], breaks = c(0:101), plot = FALSE)
  xleft <- hist_data$breaks[-length(hist_data$breaks)]
  xright <- hist_data$breaks[-1]
  ybottom <- j+0.25
  ytop <- 0.5*hist_data$counts/max(hist_data$counts) + ybottom
  rect(xleft, ybottom, xright, ytop, col = "#555555", border = NA)
}
abline(v = seq(50, 100, 10), lty = 3)
par(mar = c(4,0,2,0))
plot(0,0, type = "n", xlim = c(0, 1), ylim = c(0, 1), xlab = "", ylab = "", axes = FALSE)
feature_colors_adjusted <- feature_colors[!names(feature_colors) %in% c("LTR5")]
names(feature_colors_adjusted) <- gsub("LTR3", "LTR", names(feature_colors_adjusted))
legend("topleft", legend = names(feature_colors_adjusted), fill = feature_colors_adjusted, bty = "n", cex = 1.5)
dev.off()


Lineage <- names(te_coords)
LTR_mean_length <- round(sapply(te_coords, function(x) mean(x$LTR5[2])))
TE_mean_length <- round(sapply(te_coords, function(x) mean(x$LTR3[2])))

summary_df <- data.frame(Lineage = gsub("Class_I|LTR|", "", Lineage, fixed = TRUE),
                         Number_of_elements = Number_of_elements2[Lineage,]$N_elements,
                         TE_mean_length = TE_mean_length,
                         LTR_mean_length = LTR_mean_length,
                         Number_of_elements_with_PBS_and_TSD = Number_of_elements2[Lineage,]$N_elements_PBS_TSD,
                         Number_of_elements_with_PBS = Number_of_elements2[Lineage,]$N_elements_PBS,
                         Number_of_elements_with_TSD = Number_of_elements2[Lineage,]$N_elements_TSD,
                         Number_of_domain_clusters = Lineage_counts2[Lineage, "D"],
                         stringsAsFactors = FALSE)


write.table(summary_df, paste(opt$output, ".csv", sep = ""), sep = "\t", quote = FALSE, row.names = FALSE)
if (opt$save_all){
  save.image(paste(opt$output, ".RData", sep = ""))
}


# adjust colnames for HTML
colnames(summary_df) <- c(
    'Lineage',
    "Number of elements",
    'Element mean length <br> [bp]',
    "LTR mean length <br> [bp]",
    "Number of elements <br>with PBS & TSD",
    "Number of elements <br>with PBS only",
    "Number of elements <br>with TSD only",
    "Number of domain clusters"
)

names(output_file_names) <- gsub("Class_I|LTR|", "", names(output_file_names), fixed = TRUE)
generateHTML(output_file_names,
             paste(opt$output, ".html", sep = ""),
             folder=basename(paste(opt$output, "_plots", sep = "")),
             summary_df = summary_df[,1:7]
)


